// Generated by Wrangler by running `wrangler types`

interface Env {
	CACHE: KVNamespace;
	SESSIONS: KVNamespace;
	WEBFLOW_SITE_ID: "687bbc3b0bb3dd57d6c1fd83";
	WEBFLOW_API_URL: "https://api.webflow.com/v2";
	MEDIA: R2Bucket;
	DB: D1Database;
}
